[package]
name = "bgpd"
version = "0.1.0"
authors = ["Mat Wood <mat@thepacketgeek.com>"]
edition = "2018"

[[bin]]
name = "bgpd"
path = "src/main.rs"

[dependencies]
bgp-rs = { git = "https://github.com/thepacketgeek/bgp-rs" }
bgpd-rpc-lib = { path = "rpc_lib" }
bytes = "0.4.12"
byteorder = "1.3.1"
chrono = { version = "0.4.7", features = ["serde"] }
env_logger = "0.6.1"
itertools = "0.8.1"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", default-features = false, features = ["http"] }
futures = { version = "0.3" }
log = "0.4.6"
net2 = "0.2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.1.11"
structopt = "0.2.18"
tokio = "=0.2.0-alpha.6"
tokio-io = "=0.2.0-alpha.6"
tokio-net = "=0.2.0-alpha.6"
tokio-codec = "=0.2.0-alpha.6"
toml = "0.5"
twoway = "0.2.0"