[package]
name = "bgpd"
version = "0.1.0"
authors = ["Mat Wood <mat@thepacketgeek.com>"]
edition = "2018"

[dependencies]
bgp-rs = { git = "https://github.com/thepacketgeek/bgp-rs", branch = "message-attrs" }
byteorder = "1.3.1"
bytes = "0.4"
clap = "2.33.0"
env_logger = "0.6.1"
futures = "0.1"
log = "0.4.6"
net2 = "0.2.33"
num = "0.2.0"
serde = "1.0"
serde_derive = "1.0.92"
tokio = "0.1.21"
tokio-io = "0.1"
tokio-codec = "0.1.1"
toml = "0.5"
twoway = "0.2.0"