router_id = "1.1.1.1"       # Default Router ID for the service
default_as = 65000

[[peers]]
remote_ip = "172.16.20.1"
remote_as = 65000
passive = true              # If passive, bgpd won't attempt outbound connections 
router_id = "127.0.0.1"     # Can override local Router ID for this peer

[[peers]]
remote_ip = "127.0.0.2"
remote_as = 65000
local_as = 65000

[[peers]]
remote_ip = "::2"
remote_as = 65000
local_as = 65000
passive = true
hold_timer = 30
