router_id = "1.1.1.1"       # Default Router ID for the service
default_as = 65000
output_dir = "./"

[[peers]]
remote_ip = "127.0.0.2"
remote_as = 65000
local_as = 65000
router_id = "127.0.0.1"     # Can override local Router ID for this peer
hold_timer = 10

[[peers]]
remote_ip = "127.0.0.3"
remote_as = 65000
local_as = 65000
passive = true              # If passive, bgpd won't attempt outbound connections 
hold_timer = 30

[[peers]]
remote_ip = "::2"
remote_as = 65000
local_as = 65000
passive = true
hold_timer = 30
