router_id = "1.1.1.1"       # Default Router ID for the service
default_as = 65000
poll_interval = 5


[[peers]]
remote_ip = "127.0.0.2"
dest_port = 1179
remote_as = 65000
local_as = 65000
router_id = "127.0.0.1"     # Can override local Router ID for this peer
hold_timer = 30
families = [
    "ipv4 unicast",
    "ipv6 unicast",
    "ipv4 flow",
    "ipv6 flow",
]
passive = true              # If passive, bgpd won't attempt outbound connections

[[peers]]
remote_ip = "127.0.0.3"
dest_port = 1179
remote_as = 65000
local_as = 65000
hold_timer = 30

[[peers]]
remote_ip = "::2"
dest_port = 1179
remote_as = 65000
local_as = 65000
families = [
    "ipv6 unicast",
    "ipv6 flow",
]
passive = true