name: cargo

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: 0 5 * * 1,5

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Build cli
      run: cargo build --verbose --manifest-path examples/cli/Cargo.toml
    - name: Run tests
      run: cargo test --verbose
