name: cargo

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: 0 5 * * 1,5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
